config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :envs

  resources :apps do
    resources :configs
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'download/:app_name/:env', to: 'download#index'

  root 'apps#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/config.rb
class Config < ApplicationRecord
  belongs_to :app
  belongs_to :env
end

app/controllers/configs_controller.rb
class ConfigsController < ApplicationController
  before_action :set_app, except: [:download]
  before_action :set_config, only: [:show, :edit, :update, :destroy]

  # GET /configs
  # GET /configs.json
  def index
    @configs = @app.configs.includes(:app, :env).order(:env_id, :id)
  end

  # GET /configs/1
  # GET /configs/1.json
  def show
  end

  # GET /configs/new
  def new
    @app = App.find(params[:app_id])
    @config = Config.new(app_id: @app.id)
  end

  # GET /configs/1/edit
  def edit
  end

  # POST /configs
  # POST /configs.json
  def create
    @config = Config.new(config_params)

    respond_to do |format|
      if @config.save
        format.html { redirect_to app_config_path(@config.app, @config), notice: t('save_success') }
        format.json { render :show, status: :created, location: @config }
      else
        format.html { render :new }
        format.json { render json: @config.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /configs/1
  # PATCH/PUT /configs/1.json
  def update
    respond_to do |format|
      if @config.update(config_params)
        format.html { redirect_to app_config_path(@config.app, @config), notice: t('save_success') }
        format.json { render :show, status: :ok, location: @config }
      else
        format.html { render :edit }
        format.json { render json: @config.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /configs/1
  # DELETE /configs/1.json
  def destroy
    @config.destroy
    respond_to do |format|
      format.html { redirect_to configs_url, notice: t('delete_success') }
      format.json { head :no_content }
    end
  end

  private
    def set_app
      @app = App.find(params[:app_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_config
      @config = Config.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def config_params
      params.require(:config).permit(:app_id, :env_id, :name, :content)
    end
end

app/helpers/configs_helper.rb
module ConfigsHelper
end

app/views/configs/_form.html.erb
<%= form_with(model: [app, config], local: true, class: 'form') do |form| %>
  <% if config.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(config.errors.count, "error") %> prohibited this config from being saved:</h2>

      <ul>
      <% config.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :app_id %>
    <%= form.hidden_field :app_id, id: :config_app_id, class: 'form-control' %>
    <%= text_field_tag :app_name, app.name, class: 'form-control', disabled: true %>
  </div>

  <div class="form-group">
    <%= form.label :env_id %>
    <%= form.select :env_id, Env.all.collect { |p| [ p.name, p.id ] }, {include_blank: true}, id: :config_env_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :config_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, id: :config_content, class: 'form-control', rows: 15 %>
  </div>

  <div class="form-group">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/configs/edit.html.erb
<h2><%= t '.title' %></h2>

<%= render 'form', app: @app, config: @config %>

<%= link_to t('show'), app_config_path(@app, @config) %> |
<%= link_to t('back'), app_configs_path %>

app/views/configs/index.html.erb
<h2><%= t('.title', app: @app.name) %></h2>

<table class="table">
  <thead>
    <tr>
      <th><%= t 'app' %></th>
      <th><%= t 'env' %></th>
      <th><%= t 'filename' %></th>
      <th><%= t 'oprations' %></th>
    </tr>
  </thead>

  <tbody>
    <% @configs.each do |config| %>
      <tr>
        <td><%= config.app.name %></td>
        <td><%= config.env.name %></td>
        <td><%= config.name %></td>
        <td>
          <%= link_to t('show'), app_config_path(config.app, config) %>
          <%= link_to t('edit'), edit_app_config_path(config.app, config) %>
          <%= link_to t('destroy'), app_config_path(config.app, config), method: :delete, data: { confirm: t('delete_confirm') } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '新增配置', new_app_config_path %>

app/views/configs/new.html.erb
<h2><%= t '.title' %></h2>

<%= render 'form', app: @app, config: @config %>

<%= link_to t('back'), app_configs_path %>

app/views/configs/show.html.erb
<h2><%= t '.title' %></h2>

<dl class="dl-horizontal">
  <dt><%= t 'app' %></dt>
  <dd><%= @config.app.name %></dd>

  <dt><%= t 'env' %></dt>
  <dd><%= @config.env.name %></dd>

  <dt><%= t 'filename' %></dt>
  <dd><%= @config.name %></dd>

  <dt><%= t 'content' %></dt>
  <dd>
    <pre><%= @config.content %></pre>
  </dd>
</dl>

<%= link_to t('edit'), edit_app_config_path(@config.app, @config) %> |
<%= link_to t('back'), app_configs_path %>