config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :envs

  resources :apps do
    resources :configs
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'download/:app_name/:env', to: 'download#index'

  root 'apps#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/apps/_form.html.erb
<%= form_with(model: app, local: true, class: 'from') do |form| %>
  <% if app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :app_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h2><%= t '.title' %></h2>

<%= render 'form', app: @app %>

<%= link_to t('back'), apps_path %>

app/views/apps/index.html.erb
<h2><%= t '.title' %></h2>

<table class="table">
  <thead>
    <tr>
      <th><%= t 'name' %></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @apps.each do |app| %>
      <tr>
        <td><%= app.name %></td>
        <td>
          <%= link_to t('new_config'), new_app_config_path(app) %>
          <%= link_to t('edit'), edit_app_path(app) %>
          <%= link_to t('destroy'), app, method: :delete, data: { confirm: t('delete_confirm') } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('new'), new_app_path %>

app/views/apps/new.html.erb
<h2><%= t '.title' %></h2>

<%= render 'form', app: @app %>

<%= link_to t('back'), apps_path %>

app/views/apps/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @app.name %>
</p>

<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>