config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :envs

  resources :apps do
    resources :configs
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'download/:app_name/:env', to: 'download#index'

  root 'apps#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OneConfig</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="notice"><%= notice %></div>

    <header class="masthead">
      <div class="masthead-inner">
        <h1>One Config</h1>
        <p>分布式配置管理平台</p>
        <% if logged_in? %>
          <p>
            <label>当前用户：<%= current_user.login %></label>
            <%= link_to t('logout'), logout_path, method: 'delete' %>
          </p>
          <div class="colophon">
            <ul class="colophon-links">
              <li><%= link_to '用户管理', users_path %>
              <li><%= link_to 'APP管理', apps_path %>
              <li><%= link_to 'ENV管理', envs_path %>
              <li>
                <%= link_to '配置管理', 'javascript: void(0)' %>
                <ul>
                  <% App.all.each do |app| %>
                    <li><%= link_to app.name, app_configs_path(app.id) %></li>
                  <% end %>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      <% end %>
    </header>

    <div class="content container">
      <%= yield %>
    </div>
  </body>
</html>